### ISSUE TITLE
Loss becomes zero in the first epoch itself!

### ISSUE THREAD

**Issue by harveenchadha** [udacity/nd320-c3-3d-imaging-starter#1]
Hi,

I modified some code and it looks like loss becomes zero in the first epoch itself.

See below tensorboard screenshot:

![image](https://user-images.githubusercontent.com/30959215/81536942-06f96900-938a-11ea-89cf-f302710d3872.png)

**Comment by abhiojha8** [comment]
Please reach out to Udacity mentors via Knowledge Hub for user-specific questions.
